### ISSUE TITLE
WebRTCInterface is not defined

### ISSUE THREAD

**Issue by NeoEvaX** [luvolondon/fvtt-module-jitsiwebrtc#32]
When module is turned on Console gets the following error:
`Uncaught ReferenceError: WebRTCInterface is not defined
    at jitsirtc-legacy.js:8`

When looking inside the jitsirtc-legacy.js file this error has issue with JitisiRTCLegacyClient trying to extend WebRTCInterface, that sems to be missing or not defined.
`class JitsiRTCLegacyClient extends WebRTCInterface {`

Not sure if it is a connected issue, but my users seem to have random connection issues. Every user seems to have a chance at one of the following issues:

- Can see others, but not sharing video (just a grey box) With or without Audio
- User's audio is super blown out, and I am unable to turn down user in interface
- Cant see others at all.

This seems random. I never seem to have the issue though. Users are scattered (one in another state). I am hosting foundry on my own server (with open ports, ssl, etc). I have jitsi running on a digital Ocean server and followed guides online to get it working. All users can connect directly to the Jitsi server with no issue. 

I would use the RTC Tweaks module for users to have another window with audio/video, but most of my users are on laptops and can't see both at the same time.

Using Foudnry 0.7.5. As well as updated JitisiWebRTC Module 0.4.0.

**Comment by bekriebel** [comment]
The `WebRTCInterface` error is unrelated and can be ignored. That is only happening because of the code in place to support legacy (pre 0.7.2) Foundry versions.

The other connection issues are a concern and I will try to work on debugging them.

**Comment by NeoEvaX** [comment]
Let me know if I can provide any debugging on my end. My users are not tech savy, but I can walk them through anything needed. I was having a hard time finding any other users having the same issue, but that link I posted seems pretty spot on to the issue.

I am in the process of hosting Foundry on Digitial Ocean. I will update if that seems to fix the issue either.

**Comment by NeoEvaX** [comment]
Will open a new issue with specific issues. as Uncaught ReferenceError: WebRTCInterface is not defined at jitsirtc-legacy.js:8 does not seem to be a bug.

**Comment by eclarke12** [comment]
@bekriebel you should add a Foundry version check and then suppress the error on newer versions :)
```js
const foundryVersion = game.data.version;
if (isNewerVersion(foundryVersion, "0.7.2") // suppress the error
```

**Comment by bekriebel** [comment]
@eclarke12 I'm doing that in one section of the code already (https://github.com/luvolondon/fvtt-module-jitsiwebrtc/blob/master/jitsirtc.js#L817), however this error comes from the class declaration itself since the parent classes that I'm extending have changed between versions? Is there a way to conditionally declare the classes as done in https://github.com/luvolondon/fvtt-module-jitsiwebrtc/blob/master/jitsirtc-legacy.js#L8 and https://github.com/luvolondon/fvtt-module-jitsiwebrtc/blob/master/jitsirtc.js#L7 ? Unfortunately I can't control which module class file is imported as that's on the FVTT end and there's nothing on the roadmap for supporting conditional module source.
