### ISSUE TITLE
No Sound from other Player

### ISSUE THREAD

**Issue by UrielMhezzek** [luvolondon/fvtt-module-jitsiwebrtc#69]
Hello, Some of my player and myself have no sound-output in different Browsers. Some Players can't found a browser, that give me a sound output. Do you have some Ideas? I used my own Jitsi Server.

**Comment by bekriebel** [comment]
You have no sound, but you do have video?

Can you try connecting to the default public Jitsi Meet server?

Can you also please enable debug logging under the module settings and provide logs from the developer console from when the issue is occurring?

Thanks!

**Comment by UrielMhezzek** [comment]
Yes, i have no sound, but video works. Other player have sound. It don't only at my computer, and i am the GM. 

Where can i found the developer console? And where can i found the Log after activating it?

**Comment by bekriebel** [comment]
Can you check out sound output device settings under Configure Audio/Video? If you are the only user not receiving sound, my guess is that the output device may be incorrect.

![image](https://user-images.githubusercontent.com/183779/111679335-6dd38400-87de-11eb-85ef-d1dd64b079ca.png)

**Comment by dangerdaren** [comment]
For what it's worth, I just updated to the newest version of this module today, but last night I tried using the previous version and ran into the same issue. I could see my players but could not hear them. They could see and hear me and each other though. Once I disabled the module everything was fine.

Haven't tested the new module update yet.

**Comment by bekriebel** [comment]
Can you both also please check the A/V configuration that I mentioned above? Can you also please provide information on what browser & OS you are using?

**Comment by jsavko** [comment]
I am running into this issue today.  If I open the an incognito window as a player I can hear all the players which is super strange.  I also don't have Audio Output Device as an option on either GM or Player Client.
[image](https://user-images.githubusercontent.com/192591/113460005-1f240d80-93cc-11eb-96c2-74c2d59094f3.png)

**Comment by bekriebel** [comment]
@jsavko are you using Firefox? FF doesn't allow you to change audio output devices. Also, FF doesn't seem to play nicely with any WebRTC systems, especially Jitsi. I'd recommend using a chrome-based browser.

**Comment by jsavko** [comment]
I was using Firefox for all 3 clients. 1 GM, 2 Players.  Players could hear each other and the GM but the GM couldn't hear the players.  I just swapped the GM Client to Chrome and all 3 clients can hear each other. Not ideal but it will work for now.  

Thanks for your prompt reply.

**Comment by bekriebel** [comment]
I'd be curious what differences there may be between the three firefox users. It's possible that some extension or browser setting is causing the issue. Firefox will use whatever your system's default output device is set to, but that doesn't explain why your incognito tab seems to work.

**Comment by jsavko** [comment]
I had two of the clients running on the same machine. One in an incognito window (GM) and one in regular browser (Player).  Other player client was running on a macbook running firefox. Both player clients had all plugins disabled as that was first thought too.

Edit:
Originally the player was in the incognito window, but I swapped them thinking maybe I had missed disabling something.  The player worked regardless of which window it was in where the GM didn't work on either window. It must be a firefox conflict with something being only loaded on the GM client.

**Comment by dangerdaren** [comment]
Me and my players all run on Chrome. Our setup is usually default device, but sometimes we specify exactly what the device is if we are having problems. Nevertheless it's a game of roulette both with Jitsi and without. At any given moment, one player who could see and hear everyone will suddenly not be able to see and here 1 out 3 players. It seems completely random. Typically we wait until everyone is logged on and then start logging in and out until everyone is working. Like I said, we have this problem with or without the Jitsi module, but I picked this module up since I was told it would fix the issue.

**Comment by bekriebel** [comment]
I'm not really sure what else to suggest, @dangerdaren. One thing you could try is starting a meeting with the same people directly on https://beta.meet.jit.si, not through FVTT at all. Be sure to switch to a tile view so everyone is visible at the same time. If this also has connection issues, then there is nothing I can do from the module side because the issue would be with WebRTC and Jitsi itself.

If that does work, then the next thing that may help is enabling debug logging in the module settings and then capturing your console logs from a couple of users when the connections drop out... that may highlight why things are failing.

**Comment by caewok** [comment]
I have what seems to be the same issue as @jsavko. Here are some details:

***Setup***

Foundry 0.7.9, jitsi module 0.5.5, dnd5e 1.2.4
Server running on VM in docker on Ubuntu 20.04.
Computer 1: Mac OS X 10.15.7, Firefox 88.0.1
Computer 2: macOS 11.3.1, Chrome 90.0.4430.93
Computer 3: windows 10, Chrome 89.0.439.128

***Issue***

Using the Jitsi Beta server (or using my Jitsi VM, for that matter), Computer 1 cannot hear audio but others can hear Computer 1. Switching Computer 1 to Chrome fixes the issue. (Because Chrome does not play nicely with Computer 1, which is old, I am loathe to switch to Chrome long term.) 

Switching to Foundry webRTC fixes Computer 1 sound issue as well.

***Logs***

Here is console output from Computer 1, filtered for the phrase "jitsi": 

> Foundry VTT | Loaded localization file modules/jitsirtc/lang/en.json foundry.js:5864:15
> 2021-05-12T14:21:06.408Z [modules/browser/BrowserCapabilities.js] This appears to be firefox, ver: 88.0 Logger.js:154:22
> 2021-05-12T14:21:06.916Z [JitsiMeetJS.js] <init>:  Analytics disabled, disposing. Logger.js:154:22
> 2021-05-12T14:21:06.916Z [modules/statistics/AnalyticsAdapter.js] <dispose>:  Disposing of analytics adapter. Logger.js:154:22
> Connected to the JitsiRTCClient Audio/Video client. foundry.js:50002:13
> SdpSimulcast: using 3 layers index.js:44:12
> Halt: There are no SSRC groups in the remote description. index.js:146:16
> Imploding SIM group: 2022399840 3814628883 3735813953 index.js:159:16
> The description does not look like plan-b interop.js:328:20
> Halt: There are no SSRC groups in the remote description. index.js:146:16
> The description does not look like plan-b interop.js:328:20
> (TIME) Render audio:	 19941 JitsiRemoteTrack.js:214:16
> (TIME) TTFM audio:	 19360 JitsiRemoteTrack.js:233:16
> (TIME) Render video:	 19975 JitsiRemoteTrack.js:214:16
> (TIME) TTFM video:	 19394 JitsiRemoteTrack.js:233:16

***Other tests***

I tried downgrading to jitsi module 0.4.17, but still had the sound issue with Computer 1. 

I tried the same 3-computer setup at https://beta.meet.jit.si, and it worked fine. 

I used to be able to use the jitsi module in the past with Computer 1 using Firefox, so something has changed relatively recently (say in the last month or two.) This problem consistently occurs with this setup now.  

Thanks, and I understand if this may not be anything you can fix!

**Comment by caewok** [comment]
Follow-up on my prior comment: I determined that clearing the Firefox cache in Computer 1 fixed the sound problem. No clue why that helped, but it did, so it may be a good troubleshooting step for others as well. Thanks!

**Comment by tristobal** [comment]
I have a similar issue. Only me (the GMA) have A/V the rest of my players have only video. When they try to enable the sound an alert pops up saying they don't have permission to enable audio, but in the setup I gave them all the permissions on audio and video :cry: 
By the way, we are using the default public Jitsi Meet server.

**Comment by bekriebel** [comment]
@tristobal That sounds like a different issue. Is this the error they are seeing? 
![image](https://user-images.githubusercontent.com/183779/119049375-4bdcb600-b975-11eb-876e-a61e0611b926.png)

That error comes specifically from Foundry when the player type doesn't have permission to broadcast audio and video. By default, the "Player" level permission does not, so you either need to make your users be Trusted Players, or enable the permission for broadcast under the Foundry permissions
![image](https://user-images.githubusercontent.com/183779/119049565-8fcfbb00-b975-11eb-9900-1b91958e1f96.png)

**Comment by bekriebel** [comment]
Closing this issue due to a lack of activity. If there are still issues, please let me know.
