### ISSUE TITLE
Error loading script: lib-jitsi-meet.min.js

### ISSUE THREAD

**Issue by benbarbour** [luvolondon/fvtt-module-jitsiwebrtc#70]
When I start foundry I see no camera boxes and the console contains two errors with jitsi files in the stack trace (and no others):

![image](https://user-images.githubusercontent.com/487715/112219514-56333b80-8be2-11eb-8364-b480acd12627.png)

I didn't tweak any settings or update my jitsi server, so I assume a foundry update did this. I took the screenshot using the public server, but the only difference when using my custom one is the path to `lib-jitsi-meet.min.js`. It was working for months.

**Comment by bekriebel** [comment]
Can you try on another client or browser? I just tested this with the latest stable (0.7.9) and alpha (0.8.0) release of FVTT and it loads as expected. Also, it's possible that it was a temporary error caused by Jitsi's beta site, as it sometimes goes offline for maintenance.

If this works for other browsers or client machines, it's possible that there is a security setting on your browser that is preventing the loading of the third party script.

**Comment by benbarbour** [comment]
It happens on Chrome and Firefox.

**Comment by bekriebel** [comment]
It seems like something on your machine or network is blocking the script from loading, then. You could start by trying to go directly to the script location with your browser and see if that loads (it will just be a bunch of code in text): https://beta.meet.jit.si/libs/lib-jitsi-meet.min.js

If that works, then something is likely blocking cross-site scripts. Do you have any kind of ad or malware blockers installed? Those can sometimes be overzealous in what they block.

**Comment by benbarbour** [comment]
I can hit the script directly, both on my home computer and the cloud-VM (Digital Ocean) that I'm running foundry on, using wget or curl. I believe it only matters if the browser I'm using for loading Foundry can get it though.

**Comment by benbarbour** [comment]
Well, I don't know what caused it or what fixed it (I didn't change much since filing this), but it seems to be gone now. Guess I'll close it! :)
