### ISSUE TITLE
Error when trying to connect to jitsi

### ISSUE THREAD

**Issue by Askanor** [luvolondon/fvtt-module-jitsiwebrtc#75]
# Error when trying to connect to jitsi

- Foundry VTT version 0.7.9
- Jitsi WebRTC client Module version 0.5.5
- Jitsi Version stable-5765-1
- Docker 20.10.6
- Docker-Compose 1.29.1
- Traefik version 2.4.8

My entire server runs in Docker containers with Traefik as the reverse proxy to handle networking. Foundry and Jitsi are working fine on their own and are accessible through their respective Sub Domains. \
When I install the Module I get this error:
![error_log_foundry](https://user-images.githubusercontent.com/7889274/118799754-62184280-b89f-11eb-81c3-52e4001e0129.png)
Here are my settings for the Module:
![audio_video_settings](https://user-images.githubusercontent.com/7889274/118799843-82480180-b89f-11eb-89df-94fb7a1a4cb4.png)
![module_settings](https://user-images.githubusercontent.com/7889274/118799852-84aa5b80-b89f-11eb-9637-bff10a9916c3.png)

**Comment by bekriebel** [comment]
Hrmm... The Docker version if Jitsi does some odd things with its config.

Can you try a few things? (Do these one at a time and test between each change, please)
1. Try setting your MUC URL to `muc.meet.jitsi`
2. Try setting your Bosh URL to `https://jitsi.askanor.xyz/http-bind`
3. Try setting both 1 and 2 at the same time

If these don't work, is there any chance you could provide me temporary credentials to your jitsi server to test some things? Just the prosody login, no need for SSH or anything like that. I'm on Discord as `bekit#4213`, or feel free to email me at `fvtt-module-help@bekit.net`.

**Comment by Askanor** [comment]
send you a mail with the credentials

**Comment by bekriebel** [comment]
Okay, I think I figured out the combination that works... The issue seems to be that the docker instance is considering the primary domain to be `meet.jitsi`, so that's what your user credentials, focus, and MUC all need to be set to. Changing the following should work:

`Signaling Server Username: askanor@meet.jitsi`

`Jitsi MUC URL: muc.meet.jitsi`
`Jitsi Focus URL: focus.meet.jitsi`

![image](https://user-images.githubusercontent.com/183779/119057461-63ba3700-b981-11eb-927f-7416e3f53ac7.png)

![image](https://user-images.githubusercontent.com/183779/119057513-77fe3400-b981-11eb-9968-a36ea017e7de.png)

I'm not sure if there's a way to configure the docker instance to use your proper domain name instead of `meet.jitsi`, but using these settings allowed me to connect with the credentials that you sent.

**Comment by bekriebel** [comment]
I heard back that this seems to have resolved the issue! At some point, I may try to do some updated tutorials on the use of the docker images, since it does seem like it sets some odd parameters.

**Comment by Mazon** [comment]
thank you! for solving my big headache.
